import React, { Component } from 'react';
import { Content } from 'react-mdl'

export default class HomeContent extends Component {
    render() {
        return (
            <div className="page-content">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti consectetur quis velit consequuntur autem iste magnam reprehenderit numquam, cum nihil ducimus, iusto aperiam culpa similique rem provident doloremque obcaecati deserunt.
            </div>
        );
    }
}